# Spark default config untuk e-commerce lakehouse

spark.master                    local[*]
spark.app.name                  ecommerce-lakehouse

# Iceberg
spark.sql.extensions            org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.local         org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.local.type    hadoop

# Performance
spark.sql.shuffle.partitions    8
spark.default.parallelism       8